name: acr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - numba
  - joblib
  - pip

  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - pip:
      - mirdata
      - mir-eval
      - librosa
      - soundfile
      - tqdm
      - notebook
      - pytorch-lightning
